### ISSUE TITLE
[Snippet] ParallelRunStep and ParallelRunConfig

### ISSUE THREAD

**Issue by kovarikthomas** [Azure/azureml-cheatsheets#34]
## Proposal for the new snippet: 
Having a snippet available for both `ParalleRunStep` and `ParallelRunConfig` would help accelerate writing pipelines for scoring/training many models scenario.

## Example of the snippet:
See: https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-pipeline-batch-scoring-classification#create-the-configuration-to-wrap-the-script

**Comment by aminsaied** [comment]
Closing since snippets moved here: https://github.com/Azure/azureml-snippets/blob/main/snippets/snippets.md
