### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by konabuta** [Azure/azureml-cheatsheets#58]
Some customers in Japan request us to translate this page into Japanese. I want to contribute to create Japanese pages. Any plan to support non-English languages in this site ?

I don't know much about docusaurus, but it seems to have multi-language support. [i18n - Introduction
](https://docusaurus.io/docs/i18n/introduction)

**Comment by aminsaied** [comment]
Thanks for the feedback. Will investigate the "internationalization" feature from docusaurus.

**Comment by aminsaied** [comment]
@konabuta - we have added the skeleton for internationalization. You should be able to create japanese pages of the website under the i18n/ directory.

Please see this tutorial for how to do so: https://docusaurus.io/docs/2.0.0-alpha.71/i18n/tutorial
(As you already found!)

Thanks again!

**Comment by konabuta** [comment]
@aminsaied Thank you ! All right, I will start working on it soon.

**Comment by konabuta** [comment]
@aminsaied Could you check this comment ? Thanks.
https://github.com/Azure/azureml-cheatsheets/issues/66#issuecomment-851012309

**Comment by konabuta** [comment]
Japanese translation markdown is merged. Thanks.
