### ISSUE TITLE
Search results bug - point to ja page

### ISSUE THREAD

**Issue by aminsaied** [Azure/azureml-cheatsheets#66]
Search results are pointing to ja page even when en is selected (by default).

These links are typically broken

**Comment by konabuta** [comment]
@aminsaied Sorry for the deploy to implement Japanese pages. Let's me check this problem.

**Comment by konabuta** [comment]
@aminsaied I tried but cannot reproduce the bug. Could you the steps to reproduces ? FYI, I forked and deployed almost same github pages with i18n at https://konabuta.github.io/azureml-cheatsheets/.

**Comment by fuhuifang** [comment]
> @aminsaied I tried but cannot reproduce the bug. Could you the steps to reproduces ? FYI, I forked and deployed almost same github pages with i18n at https://konabuta.github.io/azureml-cheatsheets/.

Hi @konabuta, the algolia search key won't get updated until 24 hours after the changes are deployed. So probably you are using the same one as us (the one not aware of the Japanese page). 

Feel free to implement the Japanese version and submit a PR. We can fix the search issue after multilingual page lands.
