### ISSUE TITLE
Run History missing in sidemenu

### ISSUE THREAD

**Issue by konabuta** [Azure/azureml-cheatsheets#77]
## Which cheat sheet? Describe the issue

cheat sheet: https://azure.github.io/azureml-cheatsheets/docs/cheatsheets/python/v1/run-history/
description: This page is missing in left sidemenu. Should it be under `Azure ML Resources`?

![image](https://user-images.githubusercontent.com/3815677/126249990-c793d724-0f6b-4841-b4ec-224a93f5ab8f.png)

**Comment by aminsaied** [comment]
That used to be part of the blog section, but we decided to remove it. Thanks for pointing this out, we'll take this page down.

**Comment by konabuta** [comment]
Okay.
