### ISSUE TITLE
Summary report for `Experiment`

### ISSUE THREAD

**Issue by kyoro1** [Azure/azureml-cheatsheets#84]
## Describe the request

We have an example on checking log with [this picture](https://azure.github.io/azureml-cheatsheets/docs/cheatsheets/python/v1/logging/#viewing-metrics), and what about adding the Summary as follows?

![image](https://user-images.githubusercontent.com/6315779/135746242-144c8973-19f8-46f2-9f70-6c1ef1892544.png)

This is because the above graph is much easily checked like a kind of summary report, at first glance.

## Additional context

-

**Comment by aminsaied** [comment]
This is a good suggestion! Indeed, this view can be useful! Thanks for the suggestion
