### ISSUE TITLE
the year of CopyRight

### ISSUE THREAD

**Issue by kyoro1** [Azure/azureml-cheatsheets#87]
## Which cheat sheet? Describe the issue

We found only "2021" in the footnote. Is it better to update to include recent year?

<img width="614" alt="image" src="https://user-images.githubusercontent.com/6315779/172089562-cd8881da-5404-4ecb-a232-1cdce216fdb8.png">

**Comment by kyoro1** [comment]
Relevant codes ..?

https://github.com/Azure/azureml-cheatsheets/blob/1c472e26ed5e5e4d0232958eff49173be2159938/website/docusaurus.config.js#L81

https://github.com/Azure/azureml-cheatsheets/blob/1c472e26ed5e5e4d0232958eff49173be2159938/website/i18n/ja/docusaurus-theme-classic/footer.json#L43

**Comment by fuhuifang** [comment]
Hi @kyoro1, I'm not sure if the code works in this json file. Created a simple fix:
https://github.com/Azure/azureml-cheatsheets/pull/90
